### ISSUE TITLE
Chilipad Dock Pro support

### ISSUE THREAD

**Issue by metametapod** [PostLogical/ooler#25]
## System Information

version | core-2024.7.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31+rpt-rpi-2712
arch | aarch64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 7, 2024 at 4:01 AM
-- | --
current_recorder_run | August 12, 2024 at 5:01 PM
estimated_db_size | 0.39 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Is the Chilipad Dock Pro currently supported by this integration? I tried using mine in pairing mode but am always shown the error "No devices found on the network".

<img width="1126" alt="Screenshot 2024-08-04 at 19 10 09" src="https://github.com/user-attachments/assets/900e7d14-42f1-4496-8008-490c05029af0">

### Reproduction steps

1. Turn on Chilipad Dock Pro in pairing mode.
2. Attempt to connect.
3. See above error message.

### Debug logs

```text
https://paste.mozilla.org/mZJ6VGbq/raw
```

**Comment by PostLogical** [comment]
I would be happy to entertain a PR that includes Chilipad Dock Pro support, but I don't have one so I can't really add it myself. It might be as simple as redoing the config_flow.py file to accommodate the Chillipad since the current code searches for the word OOLER (obviously precluding any other devices). I'm closing this for now as I do not plan to fix this unless someone else who owns a Chillipad Dock Pro can offer code that works.

**Comment by PostLogical** [comment]
I would be happy to entertain a PR that includes Chilipad Dock Pro support, but I don't have one so I can't really add it myself. It might be as simple as redoing the config_flow.py file to accommodate the Chillipad since the current code searches for the word OOLER (obviously precluding any other devices). I'm closing this for now as I do not plan to fix this unless someone else who owns a Chillipad Dock Pro can offer code that works.

**Comment by metametapod** [comment]
I still have a device on-hand and can try giving it a shot this weekend.
